databases:
  - name: django_local_library
    databaseName: django_local_library
    user: yuriguchi

services:
  - type: web
    name: django_local_library
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_local_library.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_local_library
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4